import { Conversation, ToolUseBlock, Turn } from "../models";

const STRIP_WITH_CONTENT_TAGS = [
  "user_info", "system_reminder", "system_communication",
  "system_notification", "rules", "user_rules", "user_rule",
  "agent_skills", "available_skills", "agent_skill",
  "attached_files", "code_selection", "terminal_selection",
  "tone_and_style", "tool_calling", "making_code_changes",
  "citing_code", "inline_line_numbers", "terminal_files_information",
  "task_management", "mcp_file_system", "mcp_file_system_servers",
  "mcp_file_system_server", "agent_transcripts",
  "no_thinking_in_code_or_commands", "mode_selection",
  "mermaid_syntax", "sandboxing",
];

const STRIP_WITH_CONTENT_PATTERN = new RegExp(
  STRIP_WITH_CONTENT_TAGS.map((tag) => `<${tag}[^>]*>[\\s\\S]*?</${tag}>`).join("|"),
  "gi"
);

const UNWRAP_TAGS = ["user_query"];
const UNWRAP_PATTERN = new RegExp(
  UNWRAP_TAGS.map((tag) => `<${tag}[^>]*>([\\s\\S]*?)</${tag}>`).join("|"),
  "gi"
);

function cleanText(raw: string): string {
  return raw
    .replace(STRIP_WITH_CONTENT_PATTERN, "")
    .replace(UNWRAP_PATTERN, "$1")
    .replace(/\s*\n{3,}/g, "\n\n")
    .trim();
}

function formatDate(date: Date): string {
  return date.toISOString().replace("T", " ").replace(/\.\d{3}Z$/, "Z");
}

function formatTurn(turn: Turn): string {
  const header = turn.role === "user" ? "**User**" : "**Assistant**";
  const parts: string[] = [header, ""];

  for (const block of turn.blocks) {
    if (block.type === "text") {
      const safe = cleanText(block.text);
      if (safe.length > 0) {
        parts.push(safe, "");
      }
      continue;
    }

    parts.push(formatToolUse(block), "");
  }

  return parts.join("\n").trim();
}

function formatToolUse(block: ToolUseBlock): string {
  return [
    "<details>",
    `<summary>Tool: ${block.name}</summary>`,
    "",
    "```json",
    JSON.stringify(block.input, null, 2),
    "```",
    "",
    "</details>"
  ].join("\n");
}

export class MarkdownGenerator {
  generate(conversation: Conversation): string {
    const chunks: string[] = [
      "<!-- Generated by Cursor Chronicle -->",
      `# ${conversation.title} (${formatDate(conversation.createdAt)})`,
      "",
      `<!-- Session: ${conversation.id} -->`,
      `<!-- Project: ${conversation.projectName} -->`,
      `<!-- Source: ${conversation.sourcePath} -->`,
      ""
    ];

    for (const turn of conversation.turns) {
      chunks.push("---", "", formatTurn(turn), "");
    }

    return chunks.join("\n").trimEnd() + "\n";
  }
}
